# Generated by Django 5.2 on 2025-04-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=10),
        ),
    ]
